### ISSUE TITLE
admin角色定义

### ISSUE THREAD

**Issue by Donald-Nobel** [dforce-network/xswap#2]
一共两个角色：owner和admin
admin权限：call updatePair/updatePrice/updateSellRate/updateBuyRate
owner权限：admin权限 和 changeowner，changeadmin，call emergencyStop/transferOut

**Comment by willliw** [comment]
加上 auth, 用 dsGuard 來給予 admin 地址呼叫這些function 的權利。

**Comment by willliw** [comment]
function signature: 
    "e538984f": "updateBuyRate(address,uint256)",
    "9544ec58": "updatePair(address,uint256,uint256,uint256)",
    "457972de": "updatePrice(address,uint256)",
    "f3ceea99": "updateSellRate(address,uint256)"
